### ISSUE TITLE
How to Document Obj-C Block Parameters

### ISSUE THREAD

**Issue by dpanzer** [realm/jazzy#1034]
Given a method like this

```obj-c
/**
 *  Description of method
 *
 *  @param completionHandler Description of the block in general, but clumsy to have to just explain all the block's parameters in this blob of text
 */
-(void)myMethodWithCompletion:(void(^)(BOOL success))completionHandler;
```

What is the correct way to comment it such that in the resulting documentation, you are able to document not only the parameter to the method (`completionHandler`) but also the parameters to the block (in this case just `success`)

Apple seems to have no problem doing this, for example:

https://developer.apple.com/documentation/foundation/nsurlsession/1410330-datataskwithurl?language=objc

**Comment by johnfairh** [comment]
You need to write the documentation in the main body or inside the `@param` block.  You can add multiple paragraphs under the `@param` like this (exact whitespace is important):
```
/**
 *  Description of method
 *
 *  @param completionHandler Description of the block in general,
 *
 *      A paragraph explaining the parameter
 *
 *      * A bullet list about the parameter.
 *      * Another bullet.
 */
```

The Apple documentation is not generated from headerdoc -- take a look at `NSURLSession.h`.  Swift has an internal design for documenting nested params like this, but Xcode has half-implemented something different.  When this settles down we can figure out what to do with Jazzy.

The declaration you see is what libclang provides us: Clang does not seem to preserve the placeholder names in types involving a function prototype in the AST (I guess because they have no semantic value?) so I don't think it's possible to persuade it to spit them out.

**Comment by dpanzer** [comment]
Thanks for the tips, I adapted that slightly to the following:

```
/**
 *  Call this method to notify the camera controller that the user has attempted to snap a picture.
 *
 *  @param readyBlock This block will be invoked once the camera controller has obtained a suitable frame to display to the user as a preview.
 *
 *      * `UIImage *frameImg` - The frame to display as a preview
 *
 *      * `BOOL isBlurry` - A flag indicating whether the frame is below the blurry threshold
 */
- (void)userSnappedPhotoOnReady:(void(^)(UIImage *frameImg, BOOL isBlurry))readyBlock;
```

This at least demarcates the block parameters from their descriptions with text styling, if not with some official distinct layout:

![image](https://user-images.githubusercontent.com/1000133/50786918-e7789a80-1282-11e9-97b4-bae4b4081ca4.png)

I also decided to indicate the placeholder names in my comments even though clang won't spit them out, since the alternative (i.e. `UIImage* - Description`) really doesn't seem to make sense.

Thanks for the pointers.
