### ISSUE TITLE
Xcode 10.2.1 & Jazzy 0.9.6: Could not parse compiler arguments from `xcodebuild` output.

### ISSUE THREAD

**Issue by freak4pc** [realm/jazzy#1071]
Trying to update RxSwift's docs using jazzy 0.9.6, Xcode 10.2.1 and failing, even though the build succeeds:

![image](https://user-images.githubusercontent.com/605076/57556187-fda47d80-737e-11e9-9198-b7f268c95312.png)

This seems like a regression because it worked fine before for a while, would appreciate any thoughts you have.

The project is open-source so can easily be accessed here: https://github.com/ReactiveX/RxSwift

The `.jazzy.yml` is here:
https://github.com/ReactiveX/RxSwift/blob/master/.jazzy.yml

Thank you!

**Comment by johnfairh** [comment]
The idea in that project is to run `scripts/update-jazzy-docs.sh` -- this passes a bunch of options to jazzy and works fine for me.

The failure above is caused by jazzy not being given a module name and guessing one from a podspec file, in this case `RxCocoa.podspec`, and deciding to pass `--module-name RxCocoa` to sourcekitten (as seen in the screenshot,) which then fails to match build output.  The minimum thing for you to do here is `jazzy --module-name RxSwift`.

**Comment by freak4pc** [comment]
Yup, I'm aware of the script. I think it was just a permissioning issue with `jazzy` being installed with `sudo.` Sorry for the false alarm here :) Thanks.
