### ISSUE TITLE
Ambiguous guess: can't decide between ["mason", "xml"] (Rouge::Guesser::Ambiguous) on Mac OS X Catalina/Xcode 11.1. 

### ISSUE THREAD

**Issue by razvandub** [realm/jazzy#1117]
- MacOS to Catalina. 
- Xcode 11.1. 
- jazzy version: 0.11.2
- rouge version: 3.11.1
- ruby version: 2.6.0

- jazzy errors with /Library/Ruby/Gems/2.6.0/gems/rouge-3.11.1/lib/rouge/lexer.rb:178:in `guess': Ambiguous guess: can't decide between ["mason", "xml"] (Rouge::Guesser::Ambiguous).

**Comment by johnfairh** [comment]
I think this is a problem with the Rouge plugin for Redcarpet exposed by Rouge 3.7 and some sample code in your docs / readme / markdown files.

Somewhere in your project is a markdown code-block (triple-backtick delimited) that contains the string `<!DOCTYPE foo>` and does _not_ have an explicit language set.  The workaround is to add an explicit language (probably 'xml' or 'html'?).

So change from:
<pre>
/** Doc comment
```
< !DOCTYPE math>
```
*/
</pre>
to:
<pre>
/** Doc comment
```xml
< !DOCTYPE math>
```
*/
</pre>
[I had to add some spaces because I'm too dumb to escape this through GitHub markdown but I hope it's clear....]

If you track this down and it works then could you share the breaking code?

**Comment by razvandub** [comment]
Thanks for the prompt reply. 

I do indeed have a README.md that contains "<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist", yet I'm using tab-based indentation for the code blocks. Bitbucket doesn't render the README.md properly if I use "``` <language>". 

Any workaround for the tab-based indentation of the code blocks (other than removing the above code from the README)? 

Thanks.

**Comment by johnfairh** [comment]
Is it practical to downlevel to 3.6?  `gem uninstall rouge ; gem install rouge -v 3.6.0`

I'll try and get Rouge fixed.

**Comment by razvandub** [comment]
It's working fine with rouge 3.6.0 or by removing the above code. Thanks for the help.

**Comment by johnfairh** [comment]
rouge-ruby/rouge#1343

**Comment by johnfairh** [comment]
Fixed in latest Rouge 3.12.0.
