### ISSUE TITLE
Install fails (Xcode 11 + macOS 10.14)

### ISSUE THREAD

**Issue by robbiehanson** [realm/jazzy#1120]
I get the following error when trying to install jazzy:
```
Building native extensions.  This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/sassc-2.2.1/ext
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20191019-10733-17dptcw.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/sassc-2.2.1 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/sassc-2.2.1/gem_make.out
```

My understanding is that Xcode 11 changed the system Ruby... but I'm not sure what the workaround is.

**Comment by johnfairh** [comment]
Apple ships the system Ruby in two parts: the runtime ships with the O/S and the development headers ship with Xcode.

The `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include` directory is not supposed to exist -- it shows up in the error messages because the Xcode path fails to resolve.

Catalina (macOS 10.15) updates the Ruby runtime to 2.6, with the matching development package in Xcode 11 / MacOSX10.15.sdk.

So the combo of Xcode 11 and macOS 10.14 doesn't work.

Serious workarounds include:
* Reinstalling Xcode 10.2 and xcode-select'ing it while installing the gem;
* Installing a separate complete Ruby via carthage + rbenv.

Less serious workarounds include installing Catalina, and I think some people have had success in the past by renaming paths inside `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework` -- personally I'd shy away from that.

**Comment by MaartenRimaux** [comment]
It turns out that Xcode 11 comes with the macOS 10.15 SDK which includes headers for ruby 2.6 but not for macOS 10.14 ruby2.3. [This](https://stackoverflow.com/a/58231417) StackOverflow article explains how you can solve this problem.

**Comment by johnfairh** [comment]
Closing this one, nothing to do here - users with the same problem should still find the issue.

**Comment by mobilejin** [comment]
sudo gem install -n /usr/local/bin jazzy
Try doing with this one
