### ISSUE TITLE
typealias for function signature on multiple lines ignores all but 1st line

### ISSUE THREAD

**Issue by DivineDominion** [realm/jazzy#1148]
Here's what we have in ReSwift, a typealias on 2 lines:

```swift
public typealias Middleware<State> = (@escaping DispatchFunction, @escaping () -> State?)
    -> (@escaping DispatchFunction) -> DispatchFunction
```

Here's what jazzy generates:

```
public typealias Middleware<State> = (@escaping DispatchFunction, @escaping () -> State?)
```

([See our docs](http://reswift.github.io/ReSwift/master/Other%20Typealiases.html#/s:7ReSwift10Middlewarea))

I tried this with a clean install of the latest 0.13.0 and the result is the same.

**Comment by johnfairh** [comment]
For now you'll need to include all the declaration on the same line.

It's going wrong due to a cascade of historical Swift bugs unfortunately:
* Jazzy doesn't even get the multi-line decl from your source code because of #896;
* Jazzy doesn't trust the compiler's printed decl (which is complete but all on one line) because of a workaround for SR-6321.

SR-6321 was fixed in Swift 4.2 so we could maybe remove the workaround now?
Or at least teach the workaround about the possibility of a fix.

Each time I've tried to fix 896 a new problem in the Swift compiler has got in the way - will make my annual attempt this week and see how Swift 5.1 is.

**Comment by DivineDominion** [comment]
Oh man that sounds way more horrible than I would've expected. Fingers crossed!

**Comment by johnfairh** [comment]
Fixed the 'truncated' part; remaining 'should be on two lines' part is tracked by 896.

**Comment by DivineDominion** [comment]
Great, it works now 🙌 Thanks
