### ISSUE TITLE
Deploy on Gitlab

### ISSUE THREAD

**Issue by cbm-mghebaji** [realm/jazzy#1152]
Hello,

How to deploy the generated documentation on Gitlab pages ?
Many thanks

**Comment by johnfairh** [comment]
If you're asking about having your jazzy docs reference a project on GitLab instead of GitHub then for now you'll have to do it manually: customize the theme or search/replace the HTML pages and drop in an icon to replace `gh.png`.  The URL format for source is identical so the deep links for each declaration will work fine.

See #314; I would like to get round to this fairly soon.

**Comment by jstngoulet** [comment]
@cbm-mghebaji For my project, I am using a Mac as a shell Gitlab runner, then building my project using the CI/CD availability in Gitlab. 

I am making it work in two steps, but you don't need something as complex:
1) Use FastLane to configure your build scripts. This makes life loads easier.
2) Use the Gitlab examples for how to make a "GitLab Pages" site in CI/CD

You will use the output folder of your Jazzy Docs as the "public" folder in the highest level of your project. This is what GitLab reads for their pages site, similar to github. Your .yaml file will contain steps to start fastlane, including downloading the required resources.

**Comment by johnfairh** [comment]
Closing this, answered one way or the other!
