### ISSUE TITLE
Jazzy is reporting "no USR" error for conditionally compiled items.

### ISSUE THREAD

**Issue by GalenRhodes** [realm/jazzy#1221]
When there are items (functions, classes, structs, etc.) that are conditionally compiled Jazzy is still "seeing" them but reporting "no USR" errors because Xcode is not compiling those portions.  The resulting output is an empty description.

Perhaps Jazzy should ignore those items that Xcode is not compiling.

![Screen Shot 2020-09-30 at 10 08 59 AM](https://user-images.githubusercontent.com/16696128/94696815-78b85c00-0305-11eb-8a32-492e1248590a.png)
![Screen Shot 2020-09-30 at 10 08 13 AM](https://user-images.githubusercontent.com/16696128/94696931-95549400-0305-11eb-8cb9-1f50772c4156.png)
![Screen Shot 2020-09-30 at 10 09 59 AM](https://user-images.githubusercontent.com/16696128/94696955-9d143880-0305-11eb-90f9-33b2283effaf.png)

**Comment by johnfairh** [comment]
This is sort of intentional; here's why:

The declaration is missing because we don't have any declaration info from the compiler in this case -- it might be possible to get sourcekitten to dig it out of the source code but it looks like we're missing even the info about where the declaration is.

If you write a doc comment on the decl then jazzy displays that -- which could be useful if the author wants Windows users to access the docset.

You can use a `:nodoc:` doc comment (or `--skip-undocumented` if that doesn't knock out other stuff you want) to suppress this stub value if you prefer.  Consider though that even without a doc comment it might be useful for those hypothetical Windows users to have some hint that there's an API there.

The architectural solution is to merge the results from a compiler run with -DWindows and one without, tracked by #750.

**Comment by johnfairh** [comment]
Closing as answered / dup to 750.
