### ISSUE TITLE
jazzy takes an hour to generate document

### ISSUE THREAD

**Issue by kch04** [realm/jazzy#1223]
jazzy version: 0.13.5

Our iOS framework project has approximately 270 swift files. 
For each time running jazzy, it will take 60~70 minutes to parse all swift files and generate API document.
Is there any way to speed up the time?

We are using below command

>  jazzy --objc \
             --swift-version 4.0 \
             --clean --module-version 1.2.3 \
             --module MyFramework \
             --output MyDocDir

I have tried to add the --exclude flag. But seems like jazzy will still parse the file so the executing times remain as before.
> --exclude **/MySwiftFile.swift

> Parsing MySwiftFile.swift (143/269)

Here is the result I ran ruby-prof.
```
Measure Mode: wall_time
Thread ID: 1240
Fiber ID: 1220
Total: 3945.080458
Sort by: self_time

 %self      total      self      wait     child     calls  name                           location
  0.05   3945.012     2.001     0.000  3943.012     1339  *Kernel#gem_original_require    
  0.03      1.051     1.040     0.000     0.011     1639  *BasicObject#instance_eval      
  0.02      9.006     0.957     0.000     8.048   256239  *Array#each                     
  0.02      0.923     0.918     0.000     0.004   204851   <Class::File>#file?            
  0.01      0.497     0.496     0.000     0.001      845   SQLite3::Statement#step        
  0.01      0.403     0.403     0.000     0.000    67395   <Class::File>#symlink?         
  0.01      0.286     0.286     0.000     0.000   202130   <Class::File>#expand_path      
  0.01      0.264     0.264     0.000     0.000        1   <Class::FFI::DynamicLibrary>#open 
  0.01      0.256     0.256     0.000     0.000        1   JSON::Ext::Parser#parse        
  0.01      0.254     0.254     0.000     0.000   203638   <Class::File>#join             
  0.00      0.362     0.191     0.000     0.171      249  *<Module::Kernel>#load          
  0.00      0.296     0.166     0.000     0.130   151432   Mustache::Context#find_in_hash 
  0.00      0.135     0.135     0.000     0.000        1   Kernel#system                  
  0.00      0.474     0.106     0.000     0.368   159551   Mustache::Context#find         
  0.00      0.107     0.105     0.000     0.002     5802   Object#autolink_regex          
  0.00      0.106     0.103     0.000     0.003     3125   <Module::Jazzy::SourceKitten>#attribute_regexp 
  0.00      0.085     0.085     0.000     0.000    22039   String#split                   
  0.00      3.714     0.082     0.000     3.632    30423  *String#gsub                    
  0.00      0.077     0.077     0.000     0.000   527527   Kernel#is_a?                   
  0.00      3.955     0.073     0.000     3.882    21197  *Array#map                      
  0.00      0.346     0.070     0.000     0.276     9099   Mustache::Parser#scan_tags     
  0.00      3.590     0.068     0.000     3.521    94144  *Class#new                      
  0.00      0.894     0.063     0.000     0.831      105  *Kernel#require_relative    
```

**Comment by johnfairh** [comment]
Worst case jazzy should take about the same time as it takes to build your module.

A few things to start with:
* You're right about `--exclude`, it happens after the module build step because of potential dependencies between excluded and included files;
* I'm not sure about your jazzy command: what is the `--objc` about; does the `--swift-version 4.0` really work?  what version of Xcode is this trying to invoke?
* If you think the default `xcodebuild` action is doing more than just building the module target (try it and see) you want then you can pass more args, eg. `--build-tool-arguments -target,MyTarget`.
* The ruby-prof doesn't say very much.  When you eyeball the run, can you see where the bulk of the time is going between the milestones:
    1. Starting `jazzy`
    2. The `Running xcodebuild/swift build` line
    3. The first `Parsing xxx.swift` line
    4. The last `Parsing xxx.swift` line
    5. The end of the program

If it does turn out that this is just how long it takes to run against your module then you may be able to avoid the 2-3 delay by pointing `xcodebuild` at an existing DerivedData; I'm slowly working on merging a thing that will allow you to run directly against a .swiftmodule/.framework (for Swift 5.3+) that might work for you & should avoid the 1-4 delay.

**Comment by kch04** [comment]
@johnfairh
Thanks for your comment. It really helps me a lot.

- `--objc` and `--swift-version 4.0` seems like useless. I will remove them in our script.
- My Xcode version is 12.0
- I found the root cause is `BITCODE_GENERATION_MODE=bitcode` and `BUILD_LIBRARY_FOR_DISTRIBUTION=Yes` these two build settings in our project.
If the two build settings were set, jazzy will take 8~12 seconds to parse a swift file.
So I change the command below
> jazzy \
--build-tool-arguments "BITCODE_GENERATION_MODE="",BUILD_LIBRARY_FOR_DISTRIBUTION=No" \
--clean --module-version 1.2.3 \
--module MyFramework \
--output MyDocDir

The execution time improves a lot. Just running 6 minutes.

**Comment by johnfairh** [comment]
That's really interesting -- glad it worked out.
