### ISSUE TITLE
Many errors reported on valid source

### ISSUE THREAD

**Issue by dabrahams** [realm/jazzy#1361]
If you take a look at the details of [this run](https://github.com/hylo-lang/hylo/actions/runs/5932696716/job/16086957955#step:12:26), jazzy (or something it uses) is reporting many errors that I have no clue how to address.  In fact, DocC extraction [completes cleanly](https://github.com/hylo-lang/hylo/actions/runs/5932696716/job/16086957955#step:11:594) so I'm guessing these reports represent problems in jazzy.  If they're really not for user consumption at all, perhaps jazzy should swallow them.

**Comment by johnfairh** [comment]
I haven't seen these before.  They're coming from [sourcekit](https://github.com/apple/swift/blob/edd6a3b5d4ff1c442ab744daa78159bf3852c49a/tools/SourceKit/lib/SwiftLang/SwiftASTManager.cpp#L1099-L1104).  I don't know what exactly it is trying to say - usually the messages on this channel are genuinely useful compiler errors.  The message saying the 'cursor info' query is failing causes the 'has no USR' message down the line (that one is from jazzy itself) which in turn means that some symbols' documentation is missing.

I think I set up this project correctly and it looks to go well on latest Xcode 15b6 / Intel / macOS 13.4.1, eg:
```shell
; jazzy --module Driver --min-acl private
Running swift build
Parsing Diagnostic+Rendering.swift (1/7)
Parsing EnvironmentError.swift (2/7)
Parsing HyloCommand.swift (3/7)
Parsing ModulePassList.swift (4/7)
Parsing OutputFileHandle.swift (5/7)
Parsing ProcessInfo+Extensions.swift (6/7)
Parsing SourceLine+Extensions.swift (7/7)
65% documentation coverage with 35 undocumented symbols
included 102 private, fileprivate, internal, package, public, or open symbols
building site
building search index
jam out ♪♫ to your fresh new docs in `Docs`
```

So I am inclined to put this down to something fixed in Swift since the CI stack's versions.

**Comment by johnfairh** [comment]
Closing, answered/inactive.
