### ISSUE TITLE
Support autolinking more than top-level declarations

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#328]
The autolinking introduced in #324 only links top-level declarations. To make autolinking work with declarations deeper than top-level ones, we'd have to only autolink if it's on the same page (IMO).

**Comment by pcantrell** [comment]
I’ve been documenting Siesta assuming that it might eventually work as follows:

- A program element name must match a complete backticked block in order to autolink; you’ll never get links inside larger code blocks, or in plain text.
- If an element contains a dot, it matches a chain of nested elements from the top level down: `Class.method(_:foo:)`
- If an element does not contain a dot, then it either matches an element of the same parent, or a top-level element.

**Comment by pcantrell** [comment]
It’s bugging me enough that I’m getting together a PR for what I described above to see how it plays out.

Lest you all catch up with merging my submissions.

**Comment by pcantrell** [comment]
All right, so I have a draft implementation for this. It can auto-link siblings, top-level elements, and dot-separated chains:

<img width="738" alt="screen shot 2015-11-03 at 12 18 19 am" src="https://cloud.githubusercontent.com/assets/378162/10902260/c478306e-81c0-11e5-85bd-425ebc3a9fd0.png">

It allows a `(...)` for long parameter lists, and per the original implementation, does not link from an element to itself:

<img width="737" alt="screen shot 2015-11-03 at 12 18 56 am" src="https://cloud.githubusercontent.com/assets/378162/10902264/d8cf318e-81c0-11e5-8a7d-e1d0dec903d8.png">

It only links single-backticked text — nothing inside code blocks, nothing inside plain text. Here, “Configuration” happens to be the name of a struct in this project, but is used here as a plain English word in a situation where linking to the struct would be downright misleading:

<img width="734" alt="screen shot 2015-11-03 at 12 19 33 am" src="https://cloud.githubusercontent.com/assets/378162/10902291/2ee3b3ce-81c1-11e5-8024-57b0c886b50d.png">

My implementation relies on code from #289 and #310, so I guess let’s work on getting those merged and then I’ll create a PR for this.

**Comment by jpsim** [comment]
That looks good, @pcantrell!
