### ISSUE TITLE
Using existing build data for generating docs

### ISSUE THREAD

**Issue by devxoul** [realm/jazzy#330]
Hi,

I'd like to generate document on CI server, but `xcodebuild` takes too long to compile the whole project again just after the testing has done.

Can I use existing build data (which is generated during testing) for generating docs?

Thanks!

**Comment by jpsim** [comment]
> Can I use existing build data (which is generated during testing) for generating docs?

Yes, but some changes would have to be made to SourceKitten to allow that. For example, instead of passing in `xcodebuild` arguments, SourceKitten would have to support passing raw swiftc arguments.

For now, I think the simplest solution would be to run jazzy *before* your CI server builds and tests your project.

**Comment by devxoul** [comment]
@jpsim, thanks for your answer. I'll check it +1
