### ISSUE TITLE
Swift version and tvOS support

### ISSUE THREAD

**Issue by orta** [realm/jazzy#335]
Hello there, I spotted that a bunch of popular pods were failing with jazzy, as they were getting classed as a `2.0` project but were `2.1` because they supported tvOS, which requires a later build of Xcode.

I've made the conversion to default to `2.1` on CocoaDocs, but it might be prudent to do the same for everyone. More info: https://github.com/CocoaPods/cocoadocs.org/issues/399

**Comment by segiddins** [comment]
Jazzy doesn't do any thinkin here. It has a default of 2.0, and any other version needs to be specified as an option.

**Comment by orta** [comment]
Perhaps raise the default to 2.1 as that is now the version installed by the Mac App Store?

**Comment by segiddins** [comment]
@orta I think we could accept a PR doing that 😉

**Comment by jpsim** [comment]
I just cut SourceKitten "0.5.2: Grumpy Cat " with support for Xcode 7.1: https://github.com/jpsim/SourceKitten/releases/tag/0.5.2

Now, I'll be working on updating jazzy to use that as well as updating the integration fixtures too.

**Comment by jpsim** [comment]
PR in #338.

**Comment by jpsim** [comment]
Done.

**Comment by danthorpe** [comment]
Hi! Related to this issue, I'm trying to run jazzy from source using the latest master 155238c, on a framework which is Swift 2.1 and supports tvOS, including in its .podspec.

Executing it like this:

```
Ice:Money daniel$ ~/Documents/Develop/jazzy/bin/jazzy --swift-version 2.1 --module Money
Money.podspec:22:in `block in _eval_podspec':  (Pod::DSLError)
[!] Invalid `Money.podspec` file: undefined method `tvos' for #<Pod::Specification name="Money">. Updating CocoaPods might fix the issue.

 #  from Money.podspec:22
 #  -------------------------------------------
 #    s.osx.deployment_target = '10.10'
 >    s.tvos.deployment_target = '9.0'
 #    s.watchos.deployment_target = '2.0'
 #  -------------------------------------------
``` 

Which is a bit weird as I definitely have 0.39 installed. So did a bit of digging, and of course it's because the `Gemfile.lock` in the repo has `cocoa pods (~> 0.38)` so the instructions to build jazzy should probably be updated to `bundle update && bundle install`? Once that is done, it gets to the xcodebuild stage... where it crashes.

```
Ice:Money daniel$ ~/Documents/Develop/jazzy/bin/jazzy --swift-version 2.1
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/6j/9k2drdbs1fv9fw5d6wng5yzh0000gn/T/xcodebuild-58E90D6D-7757-4973-9F88-C55F8A2AE5F1.log
Failed to generate documentation
/Users/daniel/Documents/Develop/jazzy/lib/jazzy/executable.rb:35:in `execute_command': /Users/daniel/Documents/Develop/jazzy/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--module-name", "Money"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/6j/9k2drdbs1fv9fw5d6wng5yzh0000gn/T/xcodebuild-58E90D6D-7757-4973-9F88-C55F8A2AE5F1.log

Failed to generate documentation
	from /Users/daniel/Documents/Develop/jazzy/lib/jazzy/sourcekitten.rb:130:in `run_sourcekitten'
	from /Users/daniel/Documents/Develop/jazzy/lib/jazzy/doc_builder.rb:56:in `block in build'
	from /Users/daniel/Documents/Develop/jazzy/lib/jazzy/doc_builder.rb:54:in `chdir'
	from /Users/daniel/Documents/Develop/jazzy/lib/jazzy/doc_builder.rb:54:in `build'
	from /Users/daniel/Documents/Develop/jazzy/bin/jazzy:15:in `<main>'
```

I have confirmed that the underlying version of SourceKitten is 0.5.2 which is the latest. 

The xcodebuild log shows it building, but what is perhaps interesting, is that there is an aggregate target which runs a Swift script to generate a Swift file. This target is a dependency of the framework targets, and the Xcode build log seems to end at the end of this script...

```
    /bin/sh -c \"/Users/daniel/Documents/Work/danthorpe/Money/build/Money.build/Release/Generate\ Swift.build/Script-65A876DC1BE65FDA00E26F22.sh\"
Will generate currency types using: /Users/daniel/Documents/Work/danthorpe/Money/Supporting Files/Generate.swift
Will output to path: /Users/daniel/Documents/Work/danthorpe/Money/Money/Autogenerated.swift
Generate complete

** BUILD SUCCEEDED **
```

I'm wondering if what is happening is that jazzy/sourcekitten is waiting for xcode build to finish, and it's interpretation the finishing of this aggregate target to be the end?

The project I'm trying to generate docs for it: https://github.com/danthorpe/Money

Sorry for the rambling - hoping you guys know what's happening - suspect this is an uncommon issue...

Cheers,
Dan

**Comment by jpsim** [comment]
It looks like you should be providing a module name so that Xcode doesn't instead just build the dependency: `jazzy --swift-version=2.1 --module=Money`?

**Comment by danthorpe** [comment]
Hi @jpsim, thanks for getting back to me,

I did also try passing in the module name, it doesn't change the crash/error or log.

Over the weekend, I'll see if I can make a project which reproduces the error. I've since been able to get jazzy to build a different project with the same command - so pretty sure it's the dependency/ aggregate target causing the problem.
