### ISSUE TITLE
Generated docs html is escaped

### ISSUE THREAD

**Issue by jverkoey** [realm/jazzy#342]
The docs generate fine. But for some reason the content has links to &lt;a href="../Enums/.html"> strewn about. I've ran this in Nimbus' `src/core/src` directory with the following arguments:

    jazzy --objc --framework-root . --umbrella-header NimbusCore.h --module NimbusCore --output docs

This is using the freshly-landed objective-c support (which is rad, btw) :)

![screen shot 2015-11-10 at 12 47 32 am](https://cloud.githubusercontent.com/assets/45670/11055364/b5873e90-8744-11e5-9ce6-2a44ca789099.png)

![screen shot 2015-11-10 at 12 47 49 am](https://cloud.githubusercontent.com/assets/45670/11055363/b201671e-8744-11e5-84df-9a0e08c83a14.png)

**Comment by jpsim** [comment]
Whoa, that's a pretty crazy bug. I'm pretty interested in digging into this to see how this would even come to happen.

**Comment by jpsim** [comment]
So it turns out that jazzy (well `libClang`, really) thinks that the name of the `NINimbusErrorDomainCode` enum is actually an empty string, which then leads the autolinker to match every word break as a reference to this empty string enum. Yay. This is a really funny bug. I'll keep you posted as I continue to investigate this. It should be pretty easy to fix.

**Comment by pcantrell** [comment]
I have a PR coming to the autolinker that I think will fix the link-related portion of this.

**Comment by jverkoey** [comment]
Happy to help find edge cases :)

**Comment by jpsim** [comment]
This is now fixed. Thanks for reporting this funny bug. The remainder of the rendering issues are due to jazzy attempting to render your comment blocks as Markdown.
