### ISSUE TITLE
Autolink See and SeeAlso items even if no backticks

### ISSUE THREAD

**Issue by pcantrell** [realm/jazzy#363]
If `Foo` is a type, then this:

```
- See: Foo
```

…should produce the same results as this:

```
- See: `Foo`
```

Questions:
- Support any other special list items beside See and SeeAlso? Support _all_ of them?
- Should either of these also match?
  
  ```
  - See: Foo, Bar
  - See: Foo for a more foo-centric alternative
  ```
- Should we forget this, and just make people always use backticks? @jpsim says no, I also lean no.

**Comment by jpsim** [comment]
> Support any other special list items beside See and SeeAlso? Support all of them?

Support ALL THE SPECIAL LIST ITEMS.

> Should either of these also match?

```
- See: Foo, Bar
- See: Foo for a more foo-centric alternative
```

No and no. When you have more than just the type, backticks makes most sense IMO.

> Should we forget this, and just make people always use backticks? @jpsim says no, I also lean no.

"Forcing" users to use backticks isn't the worst limitation in the world, since it does provide more control over when you want to explicitly autolink, but I do think special list items should autolink if it fully matches a declaration.

**Comment by istx25** [comment]
Any progress on this?

**Comment by jpsim** [comment]
None to report.

**Comment by johnfairh** [comment]
DocC's direction is to always require the explicit link syntax so I think this is no longer a goal.
