### ISSUE TITLE
libclang: crash detected during parsing

### ISSUE THREAD

**Issue by jessesquires** [realm/jazzy#367]
Hey @jpsim  -- Trying out the newly added support for ObjC and running into issues.

##### Setup
- Jazzy `0.4.0`
- Xcode `7.1.1 (7B1005)`
- Project [`JSQSystemSoundPlayer`](https://github.com/jessesquires/JSQSystemSoundPlayer) (ObjC)

##### Script
````bash
jazzy --objc -o ./ \
      --source-directory JSQSystemSoundPlayer/JSQSystemSoundPlayer/ \
      --readme JSQSystemSoundPlayer/README.md \
      -a 'Jesse Squires' \
      -u 'https://twitter.com/jesse_squires' \
      -m 'JSQSystemSoundPlayer' \
      -g 'https://github.com/jessesquires/JSQSystemSoundPlayer'
````

##### Output
````bash
libclang: crash detected during parsing: {
  'source_filename' : ''
  'command_line_args' : ['-x', 'objective-c', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk', '-I', ''],
  'unsaved_files' : [],
  'options' : 1,
}
building site
jam out ♪♫ to your fresh new docs in `.`
````

The `README` is successfully parsed, but nothing else.

Not quite sure what this error is trying to tell me, but my guess is that's it's related to the fact that this project is iOS + OS X?

**Comment by jpsim** [comment]
Hey, I'm happy you're trying out jazzy! There are a few issues happening, one of them is a jazzy bug that has since been fixed on `master` but not officially released yet, others are due to misusing jazzy's (currently very unforgiving) Objective-C API.

First, you'll need to use jazzy from `master`, which includes #349, useful to your project since it's documented using a "wall of asterisks" style. You can build jazzy & install jazzy from source by running `bundle install && bundle exec rake install`.

From the root of your repo, I suggest you run this to generate your docs:

```bash
jazzy --objc \
      --umbrella-header JSQSystemSoundPlayer/JSQSystemSoundPlayer/JSQSystemSoundPlayer.h \
      --framework-root JSQSystemSoundPlayer/JSQSystemSoundPlayer \
      -u https://twitter.com/jesse_squires
```

You'll notice that I've added the `--umbrella-header` and `--framework-root` arguments, which are both required to build jazzy ObjC docs. This is mentioned in the README in the [ObjC usage](https://github.com/realm/jazzy#objective-c) section, but I should probably also make jazzy abort & log an error if these parameters aren't present. I'll take note to do this.

I've also removed the `-a`, `-m` and `-g` arguments because those are already picked up from the podspec in the repo :smile:.

**Comment by jpsim** [comment]
If all goes well, your docs should look something like this: http://static.realm.io/jazzy_demo/JSQSystemSoundPlayer/

**Comment by jessesquires** [comment]
Thanks @jpsim ! :smile: 

I wasn't really a huge fan of the "wall-of-asterisks" in the first place. I think it was (or still is?) the default for `VVDocumenter-Xcode` for ObjC. I decided to just ditch that style (to be consistent with Swift docs) and use the `0.4.0` release. Everything works! :+1: Final results here: http://www.jessesquires.com/JSQSystemSoundPlayer/

>I've also removed the -a, -m and -g arguments because those are already picked up from the podspec in the repo
>
>I forgot to say that I also removed the --source-directory and --readme arguments since those are unnecessary in this case.

Actually needed to keep these params, because I'm using this fancy gh-pages setup described [here](https://github.com/jessesquires/JSQSystemSoundPlayer/tree/gh-pages).
