### ISSUE TITLE
'Warning' block on naming a swift enum member 'Warning'

### ISSUE THREAD

**Issue by dfischbach** [realm/jazzy#417]
Hello,
I've defined an enum which contains  a member .Warning. This results in a broken documentation. See source code and created documentation below. Is there some kind of escaping required, to work around this problem?

````
/**
 The LogLevel to use for logging a message. All levels below a given LogLevel are dropped.
 
 - Verbose: Used for very detailed debugging and diagnostic information. Do not use in production code.
 - Debug:   Used for debugging and diagnostic information. Do not use in production code.
 - Info:    Used to report some informational things.
 - Warning: Used to report that something unexpected happened that may result in bad behavior or error.
 - Error:   The highest level, used to report an error.
 */
public enum LogLevel: Int
{
    case Verbose    = 1
    case Debug      = 2
    case Info       = 3
    case Warning    = 4
    case Error      = 5
}
````

Generated documentation:

<img width="751" alt="bildschirmfoto 2015-12-13 um 11 10 04" src="https://cloud.githubusercontent.com/assets/7476200/11766513/92073df6-a18b-11e5-9d1e-fd8b2f78d616.png">

**Comment by jpsim** [comment]
You're using the syntax to document a warning described in http://ericasadun.com/2015/06/14/swift-header-documentation-in-xcode-7/. How would you expect any system to distinguish your intentions here?

Regardless, I recommend you document your enum cases directly rather than in the parent enum documentation. See https://github.com/realm/realm-cocoa/blob/v0.96.3/RealmSwift-swift2.0/Realm.swift#L666-L690.
