### ISSUE TITLE
Swift extensions containing MARKs are unconditionally documented

### ISSUE THREAD

**Issue by kykim** [realm/jazzy#544]
Not sure what's triggering this. Posting this in hopes that someone might be able to give me a lead on how to debug this further.

**Comment by segiddins** [comment]
Could you share an example of code that triggers this happening, please?

**Comment by kykim** [comment]
[https://github.com/projectorhq/ios-sdk](https://github.com/projectorhq/ios-sdk)

I use the command
```
jazzy --clean --module-version master --min-acl public --output docs
```

Under the `Services` category, the class `APIService` is visible, even though it's an `internal` class. The other classes in that category are properly excluded.

HtH!

**Comment by jpsim** [comment]
The issue here is that Swift extensions don't have an inherent ACL, so we consider it for documentation only if it contains members that should be documented (generally declarations), but we consider `MARK` comments as "always documentable declarations". #563 should fix this.

Thanks for reporting this issue!
