### ISSUE TITLE
Question about 'Other ' prefix with custom_categories

### ISSUE THREAD

**Issue by lumaxis** [realm/jazzy#552]
I've been playing with the `custom_categories` option in jazzy a bit yesterday and was a bit surprised that it adds the "Other " prefix to _all_ categories whenever any custom category is used. From a gut feeling, I would have expected the prefix only be added to duplicate categories, i.e. when `custom_categories` also contains "Classes" for example.
Can someone shed some light on the reasoning behind this? Personally, I would vote for this feature to be either completely removed or only applied to duplicate categories. Depending on what the opinions here are, I'm happy to apply any changes if necessary :)
Thanks!

These are the code parts that add the "Other: " prefix:
https://github.com/realm/jazzy/blob/927079bc2b538eca8725eb13c3544b3146a28fc0/lib/jazzy/sourcekitten.rb#L24
https://github.com/realm/jazzy/blob/927079bc2b538eca8725eb13c3544b3146a28fc0/lib/jazzy/sourcekitten.rb#L50

**Comment by istx25** [comment]
Hi @lumaxis. Thanks for filing this issue. My apologies that no one has responded to you until now. I totally see where you're coming from. My personal opinion is that I agree with you. It definitely makes sense to only add Other on duplicated categories. With that said, I'd like to rope in @jpsim, @segiddins and @orta to hear they have to say. And PRs are always welcome.

**Comment by SteffenL** [comment]
Hello!

Since this issue has been open for quite some time now without further discussion, I wonder if this is still a valid issue that you are willing to discuss further.

Personally, I cannot see any reasons why I would want a section named "Other ..." without explicitly naming it so myself.

I have just started experimenting with jazzy and custom categories myself. I only wanted to add a "Documentation" section with links to handwritten documentation pages. Now all of the other sections (Classes, Protocols, etc) have been prefixed with "Other", making it look quite strange.

**Comment by lumaxis** [comment]
Personally, I have moved on from working on iOS things, so this is not directly relevant to me anymore. Since this also doesn't seem to be relevant for anyone else, closing.

**Comment by EdgarMaucourant** [comment]
Hi,
In case someone find this post and wonder what could be the a solution, there is actually an undocumented attribute you can use in your config file to define the value of this prefix (default to Other) set it to "" to get rid of it. Attribute name is "custom_categories_unlisted_prefix"

Edgar
