### ISSUE TITLE
New Apple docs style theme

### ISSUE THREAD

**Issue by agentk** [realm/jazzy#605]
Now that Apple has updated the documentation site style, does anybody want to see a Jazzy theme with a similar style?

It would be interesting to build it as a React based theme which loads all of the documentation as a chunk of JSON and doesn't need page reloads (not that jazzy sites are slow). This would also make searching fairly straight forward too. Jazzy already has all the moving parts it needs for creating JSON dumps of the docs too.

**Comment by lloydsargent** [comment]
As long as I don’t have to click on something to see the doc, it would make me really happy. Right now I have to click on everything in order to find what I want. Very irritating.

**Comment by lloydsargent** [comment]
Okay, I’ve modified the CSS file. But to make it easier, I went ahead and made it its own theme. You can find it here.

https://github.com/lloydsargent/JazzyThemeMod

**Comment by istx25** [comment]
@agentk Does @lloydsargent's solution suffice? I also think using React for a theme would be cool. Don't know much about it and still working but definitely seems _cool_ at the very least haha. Closing for now, feel free to re-open in case there's more to say.

**Comment by jpsim** [comment]
@lloydsargent can you share an example output from your theme? Why not make a PR adding it to jazzy?

**Comment by istx25** [comment]
SGTM! @lloydsargent @agentk @jpsim

**Comment by agentk** [comment]
With @lloydsargent's permission, I don't mind creating a PR to include the theme.

**Comment by lloydsargent** [comment]
You have my permission.

**Comment by agentk** [comment]
Cheers, I'll work on that tonight and ping you in the PR for review.

**Comment by agentk** [comment]
Is there anything significant about the name `cana`?

**Comment by agentk** [comment]
I have added and push the canna theme to: https://github.com/agentk/jazzy/tree/theme-canna.

And I think I should have been clearer about the the issue I opened. The `canna` theme only differs from the `apple` theme in the `jazzy.css.scss` file by removing the colour theming support and and changing the section styling. It would probably be better to introduce support for theme 'subclassing' to allow for just one file to be overridden instead of duplicating a whole theme for one file.

### Screen shots of the themes in Jazzy:

Theme apple:
![theme-apple](https://cloud.githubusercontent.com/assets/117041/20664553/d025450e-b5af-11e6-96fc-b2126c9a9938.png)

Theme canna:
![theme-canna](https://cloud.githubusercontent.com/assets/117041/20664554/d084d794-b5af-11e6-9745-9cdc4d0bc545.png)

Theme fullwidth:
![theme-fullwidth](https://cloud.githubusercontent.com/assets/117041/20664555/d08b885a-b5af-11e6-84e1-64d70fe23507.png)

### And the _new_ Apple documentation styling I was referring to:

Apple API Reference:
![apple-api-reference](https://cloud.githubusercontent.com/assets/117041/20664576/e84f99cc-b5af-11e6-8cd8-c8bf2c4407cc.png)

Xcode 8.1 Documentation:
![xcode-8 1-docs](https://cloud.githubusercontent.com/assets/117041/20664581/e8a91d94-b5af-11e6-92c5-a669feadf811.png)

**Comment by lloydsargent** [comment]
1. > Is there anything significant about the name canna?

It is the name of a plant/flower (Ms Google can show you what it looks like) that is dear to me as well as the name of my business, Canna Software. 

2. > And I think I should have been clearer about the the issue I opened. The canna theme only differs from the apple theme in the jazzy.css.scss file by removing the colour theming support and and changing the section styling.

If by `apple theme` you mean the `jazzy theme` it does more than that. It removes the need to “click” on a method to find out what it does. For people who need to print hard copy or create PDF’s for their classes, this can be invaluable. 

There are other, minor, aspects that differ from the previous `real apple` doc, but I’m not a CSS wizard and more than a few hours of it is enough to put me in a rubber room.

3. >It would probably be better to introduce support for theme ‘subclassing' to allow for just one file to be overridden instead of duplicating a whole theme for one file.

I agree 100%. I was surprised that Jazzy required hard-code changes to add another theme.

4. >Xcode 8.1 Documentation

I am not a fan of the new documentation. Go to NSString and you will see what I mean: previously you could go to “Finding Characters and Substrings” in the Bar. Apple removed that functionality based on the interesting belief that Swift classes will have a small number of methods.

Yeah, let me know how that works out.

Back in the old days of the OS X Beta I had to LITERALLY yell, scream, and fight with Apple that TERSE documentation is not GOOD documentation. They seemed to have learned their lesson - until 8.1 when again I see terse documentation is once again “the style”.

A friend of mine likes to quip, “Good code is hard to write - it should be hard to understand.”

Sadly, this appears to be what Apple is doing.

**Comment by jpsim** [comment]
> I agree 100%. I was surprised that Jazzy required hard-code changes to add another theme.

Part of the reason why the flow for adding themes isn't super fluid and effortless is that we've only added one theme so far! If there were more themes to add, we'd find more areas to improve that experience 😉.

That's why I'm excited at the potential of adding a new theme!

So @agentk / @lloydsargent are either of you able to make a PR adding this `canna` theme?

**Comment by WCByrne** [comment]
Any progress on this? A new theme would be a welcome addition to jazzy.

**Comment by jpsim** [comment]
Contributions are always welcome.

**Comment by WCByrne** [comment]
Agreed, just wanted to see if anyone was actively working on themes before jumping into anything.

**Comment by johnfairh** [comment]
Jony theme added since this was active, closing this one.
