### ISSUE TITLE
Enums are not documented in my Swift code.

### ISSUE THREAD

**Issue by ollieatkinson** [realm/jazzy#660]
I have the following enum:

```
    /// The aspect ratio of the image.
    ///
    /// - wide:     16:9 aspect ratio.
    /// - standard: 4:3 aspect ratio.
    public enum AspectRatio {
        case wide
        case standard
    }
```

However when I generate the documentation for this each of the cases are marked as undocumented - I am guessing I have the syntax wrong (I used the default apple documentation in Xcode 8) or jazzy is not correctly picking up the case statements. 

<img width="362" alt="aspectratio enum reference safari today at 16 57 47" src="https://cloud.githubusercontent.com/assets/1382565/18718792/a09b4d74-801c-11e6-89f7-43e9e740e472.png">

I would greatly appreciate any pointers on this, it is not a blocker and causing any technical problems but just that total documentation % is getting lower with the enums not being present.

Thanks.

**Comment by fruitcoder** [comment]
Currently I copy over what I have in the enum description for the specific cases.

```
/// The aspect ratio of the image.
///
/// - wide:     16:9 aspect ratio.
/// - standard: 4:3 aspect ratio.
public enum AspectRatio {
    /// 16:9 aspect ratio.
    case wide

   /// 4:3 aspect ratio.
   case standard
}
```

While I agree that this could be automatically parsed and added to the documentation with jazzy, XCode would still not give you a description when you just alt-click on a specific case. That's why I decided to duplicate the information.

**Comment by istx25** [comment]
I will do some digging and come back with what I find.

**Comment by jpsim** [comment]
The top comment isn't standard doc comment syntax. To document the enum members, you need to add doc comments to each.

**Comment by istx25** [comment]
I'll hand off this issue to @jpsim. He knows more about the issue than I do. Cheers!

**Comment by ollieatkinson** [comment]
Ok, is this a bug in Xcode and it's documentation tooling then?

**Comment by jpsim** [comment]
What makes you think this is a bug anywhere? You're using syntax that isn't documented anywhere as a valid way to document enums and their members.

**Comment by ollieatkinson** [comment]
To clarify this documentation is automatically generated by Xcode when you press `CMD + alt + /` above the enum. I use it to document functions, variables etc too.

**Comment by jpsim** [comment]
I see. Ok, that does change things. Thanks for clarifying that. Jazzy could certainly use that documentation if the individual members don't have doc comments.

**Comment by zsstrehli** [comment]
@istx25 Everyone agrees here that this is a real bug, I think labels should be updated. Thanks!

**Comment by johnfairh** [comment]
This was always a bit of an Apple mixup because their docs tools never understood the doc-comment format that Xcode generated.  In Xcode 15 (and possibly earlier, maybe when DocC tools started to be used to generate Xcode Quick Help) the Xcode generate-documentation action for enums _no longer_ adds the cases to the enum description.  So I'm going to close this now.
