### ISSUE TITLE
Create docs for Swift from Objective-C for Swift 2.x and 3.x

### ISSUE THREAD

**Issue by brennanMKE** [realm/jazzy#663]
Viewing docs for Swift or Objective-C would help teams which are using a framework created with one language but is being used by another. And with the naming convention changes with Swift 3 it would be very helpful to see what an Objective-C method is in Swift 3. (or even Swift 2.x)

This would be a potentially difficult feature to build out unless somehow what Apple provides can be leveraged.

When I look at an Objective-C header I can use the icon at the top-left of the editor to view a Generated Interface which is the Swift version of the code. With some docs it is possible to switch between Objective-C and Swift. Given the transition between Objective-C and Swift I believe this would be useful.

I'd be happy to help with researching options to leverage tools and services from Apple to get what is needed for a Generated Interface equivalent. I could use some tips on what to read to get familiar with what might be possible.

**Comment by brennanMKE** [comment]
I am new to AST so I am going to start learning about it to see what it provides to determine if it is capable of providing useful resources for Objective-C and Swift.

http://clang.llvm.org/docs/IntroductionToTheClangAST.html

**Comment by LeoNatan** [comment]
It should be theoretically possible, as Xcode displays imported Swift symbols when selecting "View Generated Interface".

**Comment by jpsim** [comment]
I sat down with @brennanMKE over coffee in early October to go over what it would take to make this happen. I unfortunately never wrote it down here, but I'll try to summarize now, starting with how things work currently.

# Current state of affairs

## 1. How SourceKit is dynamically linked

SourceKit is dynamically found and linked at runtime based on a number of different search priorities explained in SourceKitten's [How is SourceKit resolved?](https://github.com/jpsim/SourceKitten#how-is-sourcekit-resolved) docs.

The code that does this basically all lives in SourceKitten's [`library_wrapper.swift`](https://github.com/jpsim/SourceKitten/blob/master/Source/SourceKittenFramework/library_wrapper.swift).

In order to get type-safe APIs even with this dynamic linking, we generate code that creates static closure "proxies" that map to the symbols found from `dyld`, generating this [`library_wrapper_sourcekitd.swift`](https://github.com/jpsim/SourceKitten/blob/master/Source/SourceKittenFramework/library_wrapper_sourcekitd.swift) file.

Modifying how SourceKit is linked, initialized, and how function proxies are generated will need the most work to allow communicating with multiple versions of SourceKit.

## 2. How Swift interfaces to Clang's `CXCursor`s are generated

The code responsible for making the SourceKit request for each Objective-C declaration lives in SourceKitten's [`CXCursor.swiftInterface(compilerArguments:)`](https://github.com/jpsim/SourceKitten/blob/0.15.0/Source/SourceKittenFramework/Clang%2BSourceKitten.swift#L190-L213) method.

In a nutshell, this code does the following:

1. extracts the file path string from the `CXCursor` obtained by walking the Clang AST.
2. makes a SourceKit request to generate a Swift interface to this file, also passing in a UUID so SourceKit can cache the resulting interface.
3. extracts the [USR](http://clang.llvm.org/doxygen/group__CINDEX__CURSOR__XREF.html) that uniquely identifies the declaration whose interface we want to generate from the `CXCursor`.
4. makes a SourceKit request to find where the USR is in the newly generated Swift interface.
5. makes a SourceKit request to get "cursor info" at the position where this USR is located in the newly generated Swift interface.
6. extracts the Swift declaration that's included in the payload returned by the "cursor info" request.

This part of the code will barely have to change to accommodate interacting with multiple SourceKit versions, as all versions support this kind of interface generation.

---

# Steps to generate interfaces for multiple Swift versions

### 1. Remove all assumptions in code that SourceKit will only ever be linked and initialized once

There are a number of parts of the code in SourceKitten that assume that it'll only ever be working with a single version of Swift.

The thread-safe initialization constants are one: https://github.com/jpsim/SourceKitten/blob/0.15.0/Source/SourceKittenFramework/Request.swift#L98-L112

The fact that the [`library_wrapper_sourcekitd.swift`](https://github.com/jpsim/SourceKitten/blob/master/Source/SourceKittenFramework/library_wrapper_sourcekitd.swift) function proxies are all constants are another.

### 2. Minimize the number of times libraries are dynamically loaded and unloaded

We can't just dynamically load and unload `sourcekitd.framework` every time we're in `CXCursor.swiftInterface(...)`, switching between Swift 2.3 and 3.0 for every declaration. We'll have to do something a bit more intelligent than that, such as doing one pass for each Swift version, but this will certainly add complexity.

---

One way to address all these issues at once is to generalize `Request` and `library_wrapper_sourcekitd.swift` to be parameterized by Swift version or SourceKit path.

---

@norio-nomura has done some great work in this area of SourceKitten before, so I'd be curious to know what his thoughts are on implementing this.

**Comment by norio-nomura** [comment]
I guess that SourceKitten would be able to load multiple version of SourceKit same time, because Xcode loads them from both of `Swift_2.3.xctoolchain` and `XcodeDefault.xctoolchain` same time.

**Comment by jpsim** [comment]
> Xcode loads them from both of Swift_2.3.xctoolchain and XcodeDefault.xctoolchain same time.

Yeah, this was introduced in Xcode 8 as `SourceKit.framework`, which is itself mostly written in Swift and I surmise probably has a decent amount in common with `SourceKittenFramework.framework`. Unlike `sourcekitd.framework`, that component isn't open source.

**Comment by johnfairh** [comment]
Closing this now, it looks like we're past the era of massive changes in the objc importer (though watch the C++ support make it relevant again!)
