### ISSUE TITLE
Extension constraints including conditional conformance

### ISSUE THREAD

**Issue by andersio** [realm/jazzy#717]
Not sure if I have missed something — it seems Jazzy does not generate a section title for extensions with different constraints to differentiate themselves from each other. Is that only possible by manually adding `// MARK: -`?

**Comment by SDGGiesbrecht** [comment]
You are correct. There is no automation for this yet.

Using `// MARK: -` is exactly how I do it right now. Compare [this source](https://github.com/SDGGiesbrecht/SDGLogic/blob/3d5e3a29abef0081c53e5c41475a31fc0bf31503/Sources/SDGLogic/Other/RawRepresentable.swift#L13) and [this output](https://sdggiesbrecht.github.io/SDGLogic/Extensions/RawRepresentable.html) (2016‐12‐26).

I have even added [this custom rule](https://github.com/SDGGiesbrecht/SDG/blob/e8a087ad80bf78e8256a7957cb909a09d63ed3e6/.swiftlint.yml#L141) to [SwiftLint](https://github.com/realm/SwiftLint) so that I cannot forget to mark them.

**Comment by reitzig** [comment]
For reference.

Input:

```swift
/// Fly, you Foos!
public struct Foo<T> {
    /// Creates a new instance with a single `T`.
    public init(t: T) {}
}

public extension Foo where T == Int {
    /// Creates a new instance with the sum of many `T`.
    public init(t: T...) {
        self.init(t: t.reduce(0, {$0 + $1}))
    }
}
```

Expected output: unclear, but it should be obvious that `init(t: T...)` is only available for *some* choices of `T`.

Actual output:
![screen shot 2017-08-01 at 15 54 29](https://user-images.githubusercontent.com/4246780/28828697-c39782d2-76d1-11e7-8f03-4e8d26aa014c.png)

**Comment by SDGGiesbrecht** [comment]
This goes hand in hand with `#if` statements (#750).

**Comment by johnfairh** [comment]
I'm playing with a prototype to deal better with extensions: automatically generates sections for extension constraints as well as documenting protocol conformances added by extensions, conditional or unilateral.

So we get this kind of thing:

![Screenshot 2019-04-15 at 13 49 30](https://user-images.githubusercontent.com/26768470/56416701-96b50c80-6289-11e9-860e-790bf35e36dc.png)
...with autolinking in the constraint:
![Screenshot 2019-04-19 at 09 24 51](https://user-images.githubusercontent.com/26768470/56416738-a896af80-6289-11e9-8976-27887bcd42bd.png)

Conformances from extensions are shown alongside original type declarations:
![Screenshot 2019-04-15 at 12 55 49](https://user-images.githubusercontent.com/26768470/56416751-b3e9db00-6289-11e9-99b1-9c187190eefb.png)

And extensions of external types use the actual extension declarations rather than the extended type:
![Screenshot 2019-04-15 at 13 52 56](https://user-images.githubusercontent.com/26768470/56416795-d3810380-6289-11e9-9a12-c9ff456f6c1e.png)

![Screenshot 2019-04-19 at 10 01 34](https://user-images.githubusercontent.com/26768470/56416892-2955ab80-628a-11e9-8b16-0c339a953c10.png)

Need to write more tests and sort out dependencies but should get here.

**Comment by johnfairh** [comment]
(finally) fixed in master.
