### ISSUE TITLE
Better documentation :)

### ISSUE THREAD

**Issue by stephencelis** [realm/jazzy#77]
The README is very light on usage information and how jazzy parses documentation. Does it parse Markdown? reST? Which tokens does it support (in addition to `:param:`, `:returns:`)?

**Comment by AliSoftware** [comment]
On a side note, some flags of the CLI seems to lack documentation as well.
E.g. the `--podspec` flag does not have any description in the help banner :wink:

**Comment by jessesquires** [comment]
@jpsim - It would be cool to be able to specify the path to the `README`. 

The use case here:
I'm [working on this framework](https://github.com/jessesquires/JSQDataSourcesKit), and I run `jazzy` from the framework/module directory, but my GitHub `README` is in the root directory.

**Comment by jpsim** [comment]
I definitely agree that jazzy needs much more usage documentation.

In the meantime, you can do the opposite for now: run jazzy from the root directory with the `--source-directory DIRPATH` option.

**Comment by groue** [comment]
Closed issue #162 had specific questions:

> How can we render:
> 
> - paragraphs
> - lists
> - code blocks
> - links to the internet
> - links to other types and methods
> - bold/italic text ?

**Comment by jpsim** [comment]
The answer is essentially [Markdown](http://daringfireball.net/projects/markdown/syntax). GitHub also has a good guide: https://help.github.com/articles/markdown-basics/.

Links to other code declarations aren't yet supported, but planned (see #13).

Function parameters and return values, however are defined via [reStructuredText](http://docutils.sourceforge.net/rst.html) and look like this:

```swift
/**
    Lorem ipsum dolor sit amet.

    :param: bar Consectetur adipisicing elit.

    :returns: Sed do eiusmod tempor.
*/
func foo(bar: String) -> AnyObject { ... }
```

There's more to it than that, but this should be enough get you started. This issue is still open because I definitely agree, it would be good to document jazzy's behavior and capabilities in a more thorough and official setting.

**Comment by istx25** [comment]
What's the status on this? Can this issue be closed?

**Comment by jpsim** [comment]
No, there's a ton we could do to not just teach users how to use Jazzy, but how to even write standard Objective-C or Swift documentation comments.

Linking to Erica Sadun's blog post: http://ericasadun.com/2015/06/14/swift-header-documentation-in-xcode-7/

or her book: https://itunes.apple.com/us/book/swift-documentation-markup/id1049010423?mt=11

or NSHipster's article: http://nshipster.com/swift-documentation/

maybe more.

**Comment by istx25** [comment]
Totally! Thanks for sharing these resources. I think we should also move some of the documentation out of the `README.md` and into the Wiki and go into more depth about certain topics.

**Comment by reitzig** [comment]
Fully agreed. Without looking into the setup of ReSwift, I'd not gotten anywhere. In particular, the custom categories feature is not even mentioned!
