### ISSUE TITLE
Not parsing the container app, just the extension

### ISSUE THREAD

**Issue by mikeKane** [realm/jazzy#778]
Running the command jazzy --min-acl internal it will still not parse the classes in my main project. It finishes with 0 errors, and the README.md file gets parsed fine. 

Any ideas?

**Comment by mikeKane** [comment]
Xcode 8.3.2/Swift 3.1

**Comment by johnfairh** [comment]
Hard to be certain without seeing the project but I think this is because the app + the extension are separate swift modules.  So to get everything you would need to invoke sourcekitten twice, once for each module, then combine the sourcekitten output and pass that combined file to jazzy.

Say your app is MyApp + the extension MyAppToday.

Then `sourcekitten doc --module-name MyApp > myapp_sk.json`
And `sourcekitten doc --module-name MyAppToday > myapptoday_sk.json`
Then merge them so it's one big json array in one file.
Then do `jazzy -s merged.json`.

Would probably be a nice feature for jazzy to take multiple module names.

(If you only want the main project then `jazzy -m MyApp` will do it!)

**Comment by mikeKane** [comment]
Thanks!!!!!!

**Comment by mikeKane** [comment]
With that command, how come it doesnt read the .yaml any longer? 

I wish to exclude files.
