### ISSUE TITLE
Support reStructuredText

### ISSUE THREAD

**Issue by stephencelis** [realm/jazzy#78]
This is what Apple uses, and if you extend String, you'll be reminded that jazzy doesn't seem to support it:

![screen shot 2014-11-01 at 8 51 14 am](https://cloud.githubusercontent.com/assets/658/4872326/f4fcc472-61df-11e4-8057-2d7c55eeaaae.png)

**Comment by neonichu** [comment]
There appears to be a somewhat usable C library: <https://github.com/gradha/quicklook-rest-with-nim/tree/master/external/lazy_rest-0.2.0-c-sources-macosx-amd64-release>

**Comment by jessesquires** [comment]
As of Xcode 7, Swift docs use markdown. Is this still relevant?

**Comment by jpsim** [comment]
> As of Xcode 7, Swift docs use markdown. Is this still relevant?

It's unlikely that jazzy will ever support reST given that it's difficult to find a nice way to parse it from ruby (or Swift, for that matter) and that Swift 2.0 uses Markdown for doc comments.

If Apple was strongly supporting the continued use of Swift 1.2, I might feel otherwise, but since Swift 2.0 will really be the only way to write Swift once Xcode 7 goes GM, I feel comfortable closing this and focusing efforts on Swift 2.0.
