### ISSUE TITLE
Bullet lists swallow callouts

### ISSUE THREAD

**Issue by reitzig** [realm/jazzy#785]
I expect code like this:

```md
/**
    Some description with

     * one and
     * two items.

    - Note: Be careful! 
    - Precondition: The given string has at least three characters.
*/
```

to create a paragraph with a list and then two notes (on the top level). However, Jazzy creates this:

```html
<p>Some description with</p>
<p></p><li><p>one and</p></li>
<li><p>two items.</p>
<div class="aside aside-note">
    <p class="aside-title">Note</p>
    Be careful! <p></p>

<p></p></div>
<div class="aside aside-precondition">
    <p class="aside-title">Precondition</p>
    The given string has at least three characters.<p></p>

<p></p></div></li>
```

The last list item swallows the callouts, which can cause weird formatting, e.g. if you indent lists.
Note how also the `<ul>` tag is missing.

Also, there are lots of spurious `<p>` tags.

*Workaround:* Insert `<!-- something -->` before the callout.

**Comment by johnfairh** [comment]
The indentation used here (one more space before * than -) makes redcarpet (somewhat unexpectedly) treat the - list as a sublist of the * list.  This is why the last `</li>` is in the wrong place.

The regular list gets merged with the callouts, which causes the `<ul>` tags to get dropped, due to jazzy's creation of the callouts.  This part is fixable in jazzy.
