### ISSUE TITLE
Recommended .gitignore?

### ISSUE THREAD

**Issue by rajohns08** [realm/jazzy#837]
Is there a recommended `.gitignore` file for jazzy? I'm not sure I need to push `undocumented.json` for example.

**Comment by SDGGiesbrecht** [comment]
[Here](https://github.com/SDGGiesbrecht/SDGCornerstone/blob/84974ca80f448701e7b226a8d635303b58dfbaa0/.gitignore#L29-L31) is what [Workspace](https://github.com/SDGGiesbrecht/Workspace) provides as a default `.gitignore` for Swift projects. The highlighted lines are those that deal with Jazzy.

(The `*.tgz` line is probably no longer necessary. It was originally there to prevent sensitive details in archived instances of `undocumented.json` from being pushed accidentally, but newer versions of Jazzy no longer archive `undocumented.json` in the `.tgz` files anyway.)

**Comment by SDGGiesbrecht** [comment]
Also, if you are pushing it to GitHub Pages, you will want to add an empty `.nojekyll` file in the root folder (like [this](https://github.com/SDGGiesbrecht/SDGCornerstone/tree/84974ca80f448701e7b226a8d635303b58dfbaa0/docs)), otherwise you will get glitches where Jekyll will hide or mangle pages or resources that end up with names meaningful to Jekyll.

**Comment by jpsim** [comment]
Closing as answered.
