### ISSUE TITLE
Is there a way to suppress docset generation? (only want the output)

### ISSUE THREAD

**Issue by heidiproske** [realm/jazzy#849]
Hi, 

I'm currently using jazzy to generate just the Xcode documentation output and don't need to generate a docset. Is there a way to suppress it?

Thanks,
Heidi

**Comment by jpsim** [comment]
I'm sorry, I'm having trouble parsing what you're saying/asking 😞

> I'm currently using jazzy to generate just the Xcode documentation output

Jazzy doesn't generate Xcode documentation... we used to track that in #120, but closed the issue because as of Xcode 8.3, 3rd party docsets can no longer be imported into Xcode.

> don't need to generate a docset. Is there a way to suppress it?

Are you referring here to the Dash docset, tarball and xml files that are created in `{output_directory}/docsets/{ModuleName}.{docset,tgz,xml}`?

If you're asking if there's a way to skip generating only the files in the `docset` directory, the answer is no. However, you could generate it in a temporary directory so it doesn't "pollute" your output directory:

```bash
$ jazzy [normal parameters...] --docset-path "$TMPDIR/jazzy"
```

Or you could simply delete it after running jazzy:

```bash
$ jazzy [normal parameters...] && rm -rf docs/docsets
```

---

Please let me know if I misunderstood your request.

**Comment by heidiproske** [comment]
yes you understood, sorry about my bad terminology :) (I just meant I noticed jazzy generates both the default output and then the same set of changes in docsets/). I just want the first set (which I'm pointing my github pages to).

I've gone ahead and just updated my .gitignore to ignore the docset files :) 

Thanks @jpsim for the detailed response. I'm good now :)

**Comment by jpsim** [comment]
Ah ok, happy to help!
