### ISSUE TITLE
Class under #if are getting documented

### ISSUE THREAD

**Issue by chitranshu** [realm/jazzy#869]
I have multiple classes defined under #if 

for example 
```
#if MODULE
/// Description
public class Someclass : NSObject {
    ///  Method description
    public func foo() {
    }
}
#endif
```

While generating document i am getting following warning 
```
`foo` has no USR. First make sure all modules used in your project have been imported. If all used modules are imported, please report this problem by filing an issue at https://github.com/realm/jazzy/issues along with your Xcode project. If this token is declared in an `#if` block, please ignore this message.
```
Issue is that this class getting listed in output doc. Ideally any class defined under #if should not be listed unless we define SWIFT_ACTIVE_COMPILATION_CONDITIONS under --xcodebuild-arguments

XCode : 8.3.3
Swift: 3.1
Jazzy: 0.8.3

**Comment by SDGGiesbrecht** [comment]
Yes, @chitranshu, this is an ongoing problem. You can find a longer discussion under #750. For many projects, using `--skip-undocumented` is a viable workaround, because while the symbol declarations appear, any documentation they have gets lost, so Jazzy thinks they have no documentation. 

I will close this because there are already for more details in #750. You can track that issue as you wait for (or work on) a fix, and if you discover new nuances, you are welcome to note them there. Thank you for your feedback.
