### ISSUE TITLE
ObjC-Framework, Xcode 9.1, Module names match, using Xcodebuild arguments - Could not parse compiler arguments from `xcodebuild` output

### ISSUE THREAD

**Issue by akac** [realm/jazzy#904]
Objective-C framework. Xcode 9.1. 

I've read through numerous bug reports and Googled and tried as many of the solutions offered on here as possible to try and fix my issue. I thought I had it fixed by using a .jazzy.yaml file - but obviously not.

Here is my .jazzy.yaml file:
```
sdk: iphonesimulator
module: MyProject
module_version: 3.1.0
theme: apple
readme: README.md
hide_documentation_coverage: true

xcodebuild_arguments: [-workspace, MyProject.xcworkspace , -scheme, MyProject]

```

I've tried it with and without the sdk line. If I don't use the xcodebuild_arguments like so - I always get "can't find SDK" and it doesn't move forward either. 

> jazzy --objc --clean --sdk iphone --framework-root MyProject/ --umbrella-header MyProject/MyProject.h -mn MyProject --module-version 3.1.0

 - and I've tried tons of permutations here with no luck.

So on with the .jazzy.yaml which I like better anyway. 

```
Using config file /Users/akac60/Projects/myproject-ios-release/.jazzy.yaml
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/j1/dy4pkyqs74q_44y9ttcj_mw00000gn/T/xcodebuild-DDF3AA12-7233-41EE-8765-0CB39F0480A6.log
Failed to generate documentation
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/bin/sourcekitten ["doc", "--module-name", "MyProject", "--", "-workspace", "MyProject.xcworkspace", "-scheme", "MyProject"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/j1/dy4pkyqs74q_44y9ttcj_mw00000gn/T/xcodebuild-DDF3AA12-7233-41EE-8765-0CB39F0480A6.log

Failed to generate documentation
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/sourcekitten.rb:221:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/doc_builder.rb:66:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/doc_builder.rb:64:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/doc_builder.rb:64:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'

```

Obviously pretty similar to other reports like this…but none of the proposed solutions seem to work for me. Now, one thing I did try was I made a special Umbrella.h and copied the headers in there and removed the module name so that #import <MyProject/SomeHeader.h> became #import <SomeHeader.h> - and then I just pointed Jazzy to that umbrella header and the source path - and that *did* work…but obviously that's not something I can script and it shouldn't be what I should have to do.

The logs are here: [https://www.dropbox.com/s/nccpaby6fyvzoen/xcodebuild-DDF3AA12-7233-41EE-8765-0CB39F0480A6.log?dl=0](url)

And just to show the other side:
```
sdk: iphonesimulator
module: MyProject
module_version: 3.1.0
theme: apple
readme: README.md
hide_documentation_coverage: true
umbrella_header: MyProject/MyProject.h
objc: true
framework_root: .
```

I get 
```
Using config file /Users/akac60/Projects/myproject-ios-release/.jazzy.yaml
/Users/akac60/Projects/myproject-ios-release/MyProject/MyProject.h:8:9: fatal error: could not build module 'UIKit'
0% documentation coverage with 0 undocumented symbols
building site
building search index
jam out ♪♫ to your fresh new docs in `docs`
```

I'll keep hammering away at this but would love to get some direction. Thanks!

**Comment by akac** [comment]
More info…with this config:

```
sdk: iphonesimulator
module: MyProject
module_version: 3.1.0
theme: apple
readme: README.md
hide_documentation_coverage: true
umbrella_header: MyProject/MyProject.h
objc: true
framework_root: .
```

I get

```
Using config file /Users/akac60/Projects/myproject-ios-release/.jazzy.yaml
/Users/akac60/Projects/navigation-ios-release/MyProject/MyProject.h:16:9: fatal error: 'MyProject/MPRoute.h' file not found
0% documentation coverage with 2 undocumented symbols
included 2 symbols
building site
building search index
jam out ♪♫ to your fresh new docs in `docs`
```

I've tried all sorts of source_directory paths as well going all the way from hardcoding the path, to relative paths to the source directory…and no Bueno.

Our source dir looks like this:

```
MyProject
|--MyProject
|----MyProject.h
|----Public Classes
|------SomeFile.h
|------Model/SomeFile.h
|----Private Classes
```

**Comment by johnfairh** [comment]
On the CLI (non-yaml) errors, the pastes above say `--sdk iphone` which should be `--sdk iphonesimulator`.  And setting individual extra arguments using `--xcodebuild-arguments` doesn't work.  One of the yaml files above + accompanying output is trying to build Swift because the `objc` setting is missing :-)

The most recent results show the real problem.  If your code has `#import <MyProject/MPRoute.h>` then the compiler include path needs to be such that `MyProject/MPRoute.h` is found on there.  I'm guessing that `MPRoute.h` is inside the `Public Classes` directory of your source tree which is why the #import fails.  When Xcode builds your project it uses clang tricks (specifically header maps here I think) to add virtual mappings on top of the filesystem to make the paths resolve.

You could reverse engineer the header map incantations from the Xcode build log and pass the exact same parameters to jazzy.  (ideally we would do this for you...)  This is tricky and quite fragile.

A simpler + slightly more robust approach would be to automate the path you mention you've started down: as a build step prior to running jazzy, construct the filesystem layout that the include paths need (eg. with links) and run jazzy against that.  I appreciate this is less than ideal!

**Comment by akac** [comment]
I was able to get it to work using a fast lane script that created a custom umbrella header and then ran jazzy and then removed that header. 

There was simply no way to get it to work otherwise.
