### ISSUE TITLE
"MARK: -" before of class declaration causes the class description to be ignored

### ISSUE THREAD

**Issue by gal-orlanczyk** [realm/jazzy#919]
Hi I have a scenario like this:

```swift
/************************************************************/
// MARK: - JustAClass
/************************************************************/

/// Repesents `JustAClass`.
public class JustAClass {

}
```

This causes jazzy to ignore the description provided and I get undocumented on `JustAClass`.

**Comment by johnfairh** [comment]
The 'mark' is fine.

The problem is that `/*****/` is a doc comment under the `/**` .. `*/` style.  There are limitations and bugs right now to do with comment-merging meaning this messes up the doc comment for `JustAClass` (check Xcode quick help) which is why you get the 'undocumented'.

For now I think you should rework your ascii art a bit.

**Comment by gal-orlanczyk** [comment]
@johnfairh thanks for the quick response.
Do you have a suggestion to how it will be possible to have something similar? which ascii can solve this?

Thanks.

**Comment by johnfairh** [comment]
Anything that doesn't start `/**` is fine - eg.
```
//*****
// MARK: whatever
//*****
```

**Comment by gal-orlanczyk** [comment]
Awesome thanks!
