### ISSUE TITLE
C Structs not documented in Objc Documentation

### ISSUE THREAD

**Issue by vsanthanam** [realm/jazzy#944]
I've got several structures, but they all show up as undocumented in the generated docs. My code base is all objective-c, and I've got the swift declarations hidden

```
/**
 SKRotationRateSample is ... 
typedef struct {
    
    /**
     The timestamp of the ..
     */
    NSTimeInterval timestamp;
    
    /**
     The x value ...
     */
    double x;
    
    /**
     The y value ...
     */
    double y;
    
    /**
     The z value ...
     */
    double z;
    
} SKRotationRateSample;
```

However, C Functions and C Enumerations appear to be working just fine. It's only the structs that are getting left out in the cold.

**Comment by johnfairh** [comment]
The problem is that the code above is declaring an unnamed struct type and a `typedef` of `SKRotationRateSample` to that unnamed type. Jazzy believes all things should have a name so throws it away. Adding an extra `SKRotationRateSample` to name the struct allows libclang/sourcekitten to pick it up:
```
typedef struct Whatever {
    /* content */
} Whatever;
```
This still leads to slightly odd doc results for the `typedef` that duplicates the struct contents because of the way libclang sees things.  To avoid this split up the two parts entirely:
```
/** Struct docs */
struct Whatever {
    /* content */
};

/** Typedef docs */
typedef struct Whatever Whatever;

**Comment by vsanthanam** [comment]
I updated my code to look like this:

```
/**
 doc
 */
struct SKAccelerationSample {
    
    /**
     doc
     */
    NSTimeInterval timestamp;
    
    /**
     doc
     */
    double x;
    
    /**
     doc
     */
    double y;
    
    /**
     doc
     */
    double z;
    
};


/**
 doc
 */
typedef struct SKAccelerationSample SKAccelerationSample;
```

I've updated all the structs in my project to look like this, but that doesn't seem to have fixed it -- they're all still undocumented

**Comment by johnfairh** [comment]
For me, with latest jazzy & Xcode 9.2, and a header file containing only `@import Foundation;` followed by the code pasted above, `jazzy --objc --umbrella-header HeaderSA.h --framework-root . --sdk macosx --hide-declarations swift` works OK.
![screen shot 2018-03-02 at 09 25 38](https://user-images.githubusercontent.com/26768470/36892174-dc5f156a-1dfb-11e8-9533-1f42888ba32a.png)

Maybe double-check your structure decls are definitely included from your umbrella header?  Otherwise I think will need to see a full recreating example to figure it out.

**Comment by vsanthanam** [comment]
Ok thank you! I'll check on it tonight and revert! They're definitely declared in a header that is imported in the umbrella header.

**Comment by vsanthanam** [comment]
Works! I miss have made some mistake earlier.
