### ISSUE TITLE
Carthage Module not found

### ISSUE THREAD

**Issue by JanC** [realm/jazzy#968]
Hi,
I'm generating an API reference for a class that imports and uses a 3rd party module but jazzy cannot find that module.
```objc
@import Realm;

/// The super nice class
@interface MyClass : NSObject

/**
 * Says hello to a 3rd party object
 * @param realmObject The Realm object
 */
-(void) sayHello:(RLMPermission*) realmObject;

@end
```

The `Realm.framwork` is built using Carthage and is present in `Carthage/Build/iOS/Realm.framework`

When I run jazzy I get the error `fatal error: module 'Realm' not found`:

```
jazzy --umbrella-header MyKit/MyKit.h --framework-root MyKit --objc --sdk iphonesimulator
/Users/jan/xworkspace/temp/JazzySample/MyKit/MyClass.h:11:9: fatal error: module 'Realm' not found
100% documentation coverage with 0 undocumented symbols
included 2 symbols
building site
building search index
jam out ♪♫ to your fresh new docs in `docs`
```

and the result is a documented method `sayHello` but the 
type of the parameter is `id` / `Any`:

<img width="458" alt="screen shot 2018-05-10 at 10 24 00" src="https://user-images.githubusercontent.com/707703/39860086-561cf7b6-543c-11e8-821d-e9baba70f17f.png">

To reproduce:
- [Download this sample project](https://www.dropbox.com/s/wuxj3ogyk93dvb4/JazzySample.zip?dl=0) 
- run `carthage bootstrap`
- run `jazzy --umbrella-header MyKit/MyKit.h --framework-root MyKit --objc --sdk iphonesimulator`

**Comment by johnfairh** [comment]
Option A is to move the `@import Realm` from the header to the .m, and do `@class RLMPermission;` in the header instead.

Option B is to tell jazzy what additional flags to pass to clang so that dependencies like this get resolved (a) at all and (b) well enough to generate a decent Swift API.  In theory you can figure out what these flags are from Xcode build logs.

A patch that I need to work harder on merging produced the commands in [this gist](https://gist.github.com/johnfairh/19dacaa92810ac1439f4ba85b2ad4e74) which work for me.  You'll need to edit the absolute paths for your system and might be able to edit out more of the clang flags.  (And then use `--include`/`--exclude` to get the Realm docs out of your website...)

**Comment by JanC** [comment]
Thanks! Option A works fine

Since Option B requires absolute paths, it won't work in a CI environment.

**Comment by johnfairh** [comment]
Great.
