### ISSUE TITLE
Documentation has "Instance Reference Method" file

### ISSUE THREAD

**Issue by imbaggaarm** [realm/jazzy#986]
Hi, I'm new to Jazzy, and I don't know why documentation has a file for "Instance Reference Method" likes in images below (R2Streamer Documentation). In my case, It created a folder in Classes folder and contains a file of a method. Is this a bug? How can I control the creation of that folder/file, I just documented that method like others. Thank you.
<img width="1088" alt="screen shot 2018-06-27 at 11 44 58 pm" src="https://user-images.githubusercontent.com/22892656/41987793-72a3a116-7a64-11e8-817f-85fe0bd203a7.png">
<img width="1110" alt="screen shot 2018-06-27 at 11 45 47 pm" src="https://user-images.githubusercontent.com/22892656/41987797-75ed90a2-7a64-11e8-9214-af1c150e9a44.png">

**Comment by johnfairh** [comment]
This happens because the `getNextRange()` function is defined inside the init method ([link](https://github.com/readium/r2-streamer-swift/blob/2f1899112c5a67e6215002bcccc39309d877578b/Sources/server/WebServerResourceResponse.swift#L52)).  The inner function is not marked `public` so I think `--min-acl` was set to something lower.  You could change that param or rewrite the code to avoid the pattern.

Not sure if this is a jazzy bug -- "nested functions aren't accessible from any other scope so no point in trying to document them" vs. "we document private things if asked to"...

**Comment by imbaggaarm** [comment]
Thank you. But in my case, I write a function without init method. At first, I don't write anything in that, just a blank function, I create documentation, set --min-acl to internal in config file, and see like I said before. After that, I write some code in that function, but it still creates as same before. Of course it's not affecting a lot to the document, but I still wonder what it is.

**Comment by johnfairh** [comment]
Ok; if this is happening without nested functions then please post some code so we can recreate it.
I also noticed the screenies above mention an old version of jazzy - give it a go on latest.

**Comment by johnfairh** [comment]
Closing, inactive.
