### ISSUE TITLE
‘Other’ category pages should be alphabetized

### ISSUE THREAD

**Issue by friedbunny** [realm/jazzy#991]
Catch-all pages like “Other Constants” have their members alphabetized in the navigation menu, but not in the body of the page. Since source/project order isn’t particularly meaningful for these “Other” categories in non-trivial projects, they should be be alphabetized in both places.

| <img width="250" alt="screen shot 2018-07-06 at 4 31 40 pm" src="https://user-images.githubusercontent.com/1198851/42399107-897c99d8-813a-11e8-817c-5e89b15903b4.png">  | <img width="300" alt="screen shot 2018-07-06 at 4 31 14 pm" src="https://user-images.githubusercontent.com/1198851/42399102-834cf6ac-813a-11e8-8442-d8900d3255fe.png">  |
|---|---|
| _Navigation menu_ | [_Body of Other Constants_](https://www.mapbox.com/ios-sdk/api/4.1.1/Other%20Constants.html) |

**Comment by johnfairh** [comment]
Going to close this one: the way it works is intentional, sourcefile+declaration order used for the right-hand screen (I think of it as an LP nod but that might just be me).  I do take the point being raised but at this point in Jazzy's lifecycle I don't think an alternative layout algorithm is on the cards.
