### ISSUE TITLE
Jazzy ignores markup inside double quotes?

### ISSUE THREAD

**Issue by iDave2** [realm/jazzy#992]
Hi all,

I just installed jazzy 0.9.3 using Xcode 9.4.1 command-line toolset, then returned to Xcode 10.0 beta 2 environment where my project lives.  (Jazzy would not install with the 10.0 tools.)

I am seeing the following in case it is helpful:

1. Jazzy ignores markup inside "double-quoted text" while Quick Help handles this fine.

2. Both jazzy and quick help respect markup 'inside single quotes' (so grammatically odd but a temporary workaround).

3. Jazzy handles ``TeX-like quotes'' nicely but Xcode is clueless about these.

Also tried on small 9.4.1 project and toolset, same result.

Regards,
Dave.

**Comment by iDave2** [comment]
A plethora of workarounds.

I'm still voting for keyboard quotes.  ;)

**Comment by SDGGiesbrecht** [comment]
> A plethora of workarounds.
>
> I'm still voting for keyboard quotes. ;)

*[amused laughter]* They are themselves a workaround—100 years have passed and your keyboard still hasn’t been fixed.

But anyway, it was never my intent to suggest that Jazzy has an excuse for tripping up like that. It does need fixing.

**Comment by johnfairh** [comment]
The issue here is about something like `"cut the *red* wire"`.   Jazzy displays the asterisks literally instead of applying `<strong>`.  Other markdown renderers, quick help in particular, do the italics.

This turns out to be because we are passing the `quote` option to Redcarpet.  This makes Redcarpet emit `<q>` tags and whatever is between double-quotes verbatim.

Without the `quote` option, we end up with `&ldquo;` and `&rdquo;` entities and the markup honoured.

I think we should change this, even though it's long-standing behaviour: I understand the semantic/accessibility nature of `<q>` but for our purposes and compatibility with Xcode it's worth it.

The TeX-like quotes are a Redcarpet/CMark difference for once in our favour.

**Comment by jpsim** [comment]
> I think we should change this, even though it's long-standing behaviour: I understand the semantic/accessibility nature of `<q>` but for our purposes and compatibility with Xcode it's worth it.
> 
> The TeX-like quotes are a Redcarpet/CMark difference for once in our favour.

👍 I'm in favor of this.
