### ISSUE TITLE
Possible changes to Parameters and SeeAlso

### ISSUE THREAD

**Issue by justasandiegoguy2018** [realm/jazzy#996]
First off, I'm new to both Jazzy and Github, so please forgive any trangressions.

I have found (and others have mentioned) that PARAMETERS: doesn't work at all
and I have found that the "- parameter text : text" syntax only works IF the class/function being documented actually has parameters...  I feel the documentation should say what I want, and not decide for itself if something should or should not be included.
also, if anything NOT preceded by "-" follows the parameters data, it gets rolled into the description

In regards to SEEALSO.....  I would like these to be documented at the END, where now it seems to move them to the beginning regardless of where I place them.

**Comment by SDGGiesbrecht** [comment]
@justasandiegoguy2018,

There appears to be at least some confusion, but maybe there are bugs mixed in as well. Let’s look at each thing one at a time:

(For reference, here is the official [Swift Documentation Markup](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_markup_formatting_ref/index.html#//apple_ref/doc/uid/TP40016497-CH2-SW1) guide.)

***

1. > I have found (and others have mentioned) that PARAMETERS: doesn't work at all

All official documentation and examples I have seen (particularly the above guide, the [Swift Programming Language](https://docs.swift.org/swift-book/) guide, and the [API Design Guidelines](https://swift.org/documentation/api-design-guidelines/)) use either `Parameters` or `parameters`—note the casing. Both of these do work in Jazzy.

This is the first time I have heard of someone trying to use `PARAMETERS`. However, a quick check revealed that Xcode (and SourceKit) do recognize all three, so I imagine a pull request to check for uppercase variants would be welcome.

2. > "- parameter text : text" syntax only works IF the class/function being documented actually has parameters

The parameter list does not belong to the “discussion” section. See the section of the guide titled [Ordering of Content](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_markup_formatting_ref/AddingMarkup.html) (scroll down). The parameter list (including names, types, default values, etc.) comes from the function declaration. Only the text descriptions come from the markup. As far as I know, what happens when the two disagree is undefined. In any case, Xcode does not display them either.

Whatever information you want to display could be included in the discussion instead by formatting it as a normal list and not a callout:

```swift
/// Parameters:
/// - `parameterOne`: A description of `parameterOne`.
/// - `parameterTwo`: A description of `parameterTwo`.
```

3. > if anything NOT preceded by "-" follows the parameters data, it gets rolled into the description

It is not clear to me what you mean by this (especially what you mean by “description”). The following is how it is supposed to work and how Xcode does it:

```swift
/// The first paragraph is the symbol *description*.
///
/// Subsequent paragraphs are the symbol *discussion*.
///
/// - Parameter parameterOne: This is the description of the parameter.
///
///   This is an additional paragraph further describing `parameterOne`.
///   Note the matching indentation.
///
/// This paragraph no longer has anything to do with the parameter.
/// It is a continuation of the discussion section.
/// Note that the indentation is back to what it was before.
```

4. > In regards to SEEALSO..... I would like these to be documented at the END, where now it seems to move them to the beginning regardless of where I place them.

`SeeAlso` belongs to the “discussion” section. `Parameters` and `Returns` are distinct sections outside of the discussion (regardless of where they appear in the markup source).

The order will always be the following:

1. Description
2. Discussion
3. Parameters
4. Throws
5. Returns

(See the above ordering link as well as the [Formatting](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_markup_formatting_ref/SymbolDocumentation.html#//apple_ref/doc/uid/TP40016497-CH51-SW1) section.)

However, within the discussion, `SeeAlso` will not be reordered. If you put it at the end of the discussion, it will be at the end of the discussion. You just cannot force it beyond the end of the discussion section.

***

You are welcome to report back if anything is still unclear or if you find situations where Jazzy is actually failing to do what is described above.

**Comment by SDGGiesbrecht** [comment]
> First off, I'm new to both Jazzy and Github [...]

Then we wish you a warm welcome. We are glad you are here to participate.

**Comment by johnfairh** [comment]
Closing this one now, answered - I'll add that upper-case callout names do work as far as I can tell, eg.
```
- PARAMETERS:
    - a: stuff
```

**Comment by justasandiegoguy2018** [comment]
If that was something I created, then I had totally forgotten about it....
since I had go ahead and wrote my own version of a program that does all
the same and more.... So please delete any/all contact information you
might have, as I am no longer interested.
